### ISSUE TITLE
Expand Search To Key Items

### ISSUE THREAD

**Issue by scoobwrx** [ThornyFFXI/FindAll#3]
Extend FindAll's search/find capabilities to look for key items.

**Comment by ThornyFFXI** [comment]
This has been implemented in 1.13.

**Comment by TeoTwawki** [comment]
Why the requirement to prefix with `ki:` to search them? common usage on both the v3 and windower versions was just `/findall primer` and I'd see both `a copy of Perih's primer` (item) and `Ambuscade Primer Volume One` (key item)

(2 words: muscle memory)

Also it keeps finding `a okadomatsu in name's inventory` instead of said ambuscade primer. Which I do not have in my inventory.

**Comment by ThornyFFXI** [comment]
This comment is awfully pushy, especially considering I have no affiliation with and took no part in the windower counterpart(which is also what v3 was using).  Your presumption that your own muscle memory exceeds the value of ashita4 users' muscle memory is not reasonable, and adding it to the search with no qualifier changes the behavior of the plugin for existing users.  Further, since both the gui mode and the games chat log have very limited screen real estate, it likely reduces convenience to add extra results that are not wanted to an existing search.

I will certainly look into the actual bug first thing in the morning.  I likely forgot to alter the output for log based display, but if this was using the gui please confirm.

**Comment by TeoTwawki** [comment]
> This comment is awfully pushy,

I am sometimes oblivious, I do not mean to be pushy, merely finding out why while explain my reasoning for asking. I apologize that I came off as pushy Thorny. ~~I will say however, your plugin is newer than those old addons, and the feature itself is new to your plugin so I don't understand why existing users would be impacted.~~ I presumed you had a more technical reason. _you know what, I did not at all imagine anyone would have a problem with showing BOTH together._

And I was using log based display.

**Comment by ThornyFFXI** [comment]
Existing users would be effected because their searches for plain items would be cluttered with additional unnecessary key items when names overlap at all.

I can compromise by adding a setting that defaults to disabled, which will remove the prefix when enabled.

**Comment by ThornyFFXI** [comment]
Both of these concerns should be addressed in 1.14.  If there are any remaining issues, please open a new ticket.
